oneKey:
    moreKeys: ENC[AES256_GCM,data:QE+872VD,iv:CsQbZBL6Yqz+VeZs8OzFpw0YEkE+RSRTbNJMtt+O7Pg=,tag:X3DV4mrTzZh0RplZX+4o2g==,type:str]
    another:
    - ENC[AES256_GCM,data:saTsClA=,iv:GnjUsS3HfZI22AGry8sCQ4bLIXo0O0F78rv16A04pHc=,tag:qwNFRaYfYTf4RDc4EpFWWg==,type:str]
    - ENC[AES256_GCM,data:6DHijbIf,iv:kCWOksougmsq2SQsplm5nwRnSYya2TtPzvq/N++VEJo=,tag:w7gI0NU69NR7VoKAxo1ppw==,type:str]
twoKey: ENC[AES256_GCM,data:gHfArRY=,iv:8Xn/NZQcn02U94rFJbpskXcjIzQS86ANSCzJRAENNNw=,tag:CLBF4TbNtWBW3ZqdmCjsOQ==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:264606497040:key/63d19dca-df4a-4f7b-8d60-5c70d080bbc6
        created_at: '2017-10-17T17:49:54Z'
        enc: AQECAHjyZFUi6ejyL3Q7XkoZ8ogRNW+kQgEcGB4RxEba+1kRTAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDOWc+WivVvE6B8BU6QIBEIA7Ql/XuV7t65cboqSUV4SA6W+idyH5dtY+w0Ht8JjIADqbN9waHjKcP8fl4s7SgbhV7HUQnsPYRxbe9nI=
    gcp_kms: []
    lastmodified: '2017-10-17T23:05:18Z'
    mac: ENC[AES256_GCM,data:vW7UsxWp5cktbrG+RFBXicG29XGGZi1pmd/Pkv5RfIuCAp2/hasLMzqaJoP4yOfAsachSr6nfdOLAkzcGD4hbXPOzuX4jFpnEe1/fsZ8NKUINp8cgZCjBmrtJtwrYejskYVjF1NtCvWDrm81N8SV7WAszhjc5aI+7jsCgaF/raU=,iv:ba+kCsORq3wHtk252W3oHmQwckB2+4Ji8SPS29Xx5iE=,tag:w7OrJHHYKreu3LzXxaj7Xw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.0.0
