oneKey:
    moreKeys: ENC[AES256_GCM,data:ik5EkXzX,iv:CsQbZBL6Yqz+VeZs8OzFpw0YEkE+RSRTbNJMtt+O7Pg=,tag:+5thjlQPb/aryKUzWgQfxA==,type:str]
    another:
    - ENC[AES256_GCM,data:GRzMtqg=,iv:GnjUsS3HfZI22AGry8sCQ4bLIXo0O0F78rv16A04pHc=,tag:ByO5vQEx7A4dwlKk+GDUgQ==,type:str]
    - ENC[AES256_GCM,data:MWqSy8ha,iv:kCWOksougmsq2SQsplm5nwRnSYya2TtPzvq/N++VEJo=,tag:dezF97zYR2XKqYfKi1u9+Q==,type:str]
twoKey: ENC[AES256_GCM,data:4YLZ3YY=,iv:8Xn/NZQcn02U94rFJbpskXcjIzQS86ANSCzJRAENNNw=,tag:hPOqAtgNLD0Pz6XCQxzLug==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:264606497040:key/63d19dca-df4a-4f7b-8d60-5c70d080bbc6
        created_at: '2017-10-17T17:49:54Z'
        enc: AQECAHjyZFUi6ejyL3Q7XkoZ8ogRNW+kQgEcGB4RxEba+1kRTAAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDE2wyIEK2O63MHUKZwIBEIA7XOp6C0RzCutwvgFrxYcRwy3sNBjnNVGmDsRgu1uvA1V2FF8BLWAh/r4IwCjjHQafNYY+612aLFl2/Ww=
    gcp_kms: []
    lastmodified: '2017-10-30T22:10:44Z'
    mac: ENC[AES256_GCM,data:TkelvAprUD2efplot9Zsh3XdioKqX/c9LUZ5V7kl0Jua+CiepPFVccB2Zim6pQe65tj20zSvhHrhh4dGXKO/8p1c4roXmzcSJG3prqBCTsobOY0BYGdFxfHaD/EbE7K6pO/xF3TuJDgxrrL7i/dZ3Yr6fldq6A7r+NZ8sq8xEKM=,iv:B0Hxii7yS0t0VOXdV1KwDCbFrwLAgXZ0OASiJwltfHg=,tag:puYb1Csqo/2M9QlgHxGM2Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.0.0
