run:
  timeout: 2m

linters:
  disable-all: true
  enable:
    # defaults
    - govet
    - staticcheck
    - gosimple
    - typecheck
    - revive
    # additional
    - goimports
    - gosec
    - misspell
    - whitespace

output:
  format: colored-line-number
