report_sizes: true

# Build customization
builds:
  - env:
      - CGO_ENABLED=0
    binary: sopstool
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - ""
    goamd64:
      - ""

universal_binaries:
  - id: sopstool
    # Whether to remove the previous single-arch binaries from the artifact list.
    # If left as false, your end release might have both several macOS archives:
    # amd64, arm64 and all.
    replace: true

archives:
  - id: newzips
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  name_template: "{{ .ProjectName }}_checksums.txt"

sboms:
  - artifacts: binary

nfpms:
  - id: default
    # You can change the file name of the package.
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    vendor: Ibotta
    homepage: https://github.com/Ibotta/sopstool
    maintainer: Ibotta <oss@ibotta.com>
    description: "A multi-file wrapper for Mozilla sops"
    license: Apache 2.0
    # Formats to be generated.
    formats:
      - deb
      - rpm
      - apk
    # Packages your package depends on.
    dependencies:
      - sops

brews:
  - ids:
      - newzips
    tap:
      # Repo to push the tap
      owner: Ibotta
      name: homebrew-public
    # Git author used to commit to the repository.
    commit_author:
      name: sopstoolGoreleaser
      email: oss@ibotta.com
    # Folder inside the repository to put the formula.
    folder: Formula
    # caveats: "How to use this binary"
    homepage: "https://github.com/Ibotta/sopstool"
    description: "A multi-file wrapper for Mozilla sops"
    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # Default is false.
    skip_upload: false
    # Packages your package depends on.
    dependencies:
      - sops
    # So you can `brew test` your formula.
    test: |
      system "#{bin}/sopstool version"
    install: |
      bin.install "sopstool"

blobs:
  - provider: s3
    # Bucket name (without the s3:// prefix)
    bucket: oss-pkg.ibotta.com
    # AWS Region to use.
    region: us-east-1
    # Default: '{{ .ProjectName }}/{{ .Tag }}'
    folder: "{{ .ProjectName }}/{{ .Tag }}"
  - provider: s3
    bucket: oss-pkg.ibotta.com
    region: us-east-1
    folder: "{{ .ProjectName }}"
    extra_files:
      - glob: ./*install.sh

publishers:
  - name: docker-buildx
    cmd: ./scripts/deploy-docker {{ .Major }} {{ .Minor }} {{ .Patch }}
  - name: deploy-sops
    cmd: ./scripts/deploy-sops
