# Build customization
builds:
  - env:
      - CGO_ENABLED=0
    binary: sopstool
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - ""
    goamd64:
      - ""

universal_binaries:
  - id: sopstool
    # Whether to remove the previous single-arch binaries from the artifact list.
    # If left as false, your end release might have both several macOS archives:
    # amd64, arm64 and all.
    replace: true

archives:
  - id: newzips
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  name_template: "{{ .ProjectName }}_checksums.txt"

sboms:
  - artifacts: binary

nfpms:
  - id: default
    # You can change the file name of the package.
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    vendor: Ibotta
    homepage: https://github.com/Ibotta/sopstool
    maintainer: Ibotta <oss@ibotta.com>
    description: "A multi-file wrapper for Mozilla sops"
    license: Apache 2.0
    # Formats to be generated.
    formats:
      - deb
      - rpm
      - apk
    # Packages your package depends on.
    dependencies:
      - sops

brews:
  - ids:
      - newzips
    tap:
      # Repo to push the tap
      owner: Ibotta
      name: homebrew-public
    # Git author used to commit to the repository.
    commit_author:
      name: sopstoolGoreleaser
      email: oss@ibotta.com
    # Folder inside the repository to put the formula.
    folder: Formula
    # caveats: "How to use this binary"
    homepage: "https://github.com/Ibotta/sopstool"
    description: "A multi-file wrapper for Mozilla sops"
    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # Default is false.
    skip_upload: false
    # Packages your package depends on.
    dependencies:
      - sops
    # So you can `brew test` your formula.
    test: |
      system "#{bin}/sopstool version"
    install: |
      bin.install "sopstool"

blobs:
  - provider: s3
    # Bucket name (without the s3:// prefix)
    bucket: oss-pkg.ibotta.com
    # AWS Region to use.
    region: us-east-1
    # Default: '{{ .ProjectName }}/{{ .Tag }}'
    folder: "{{ .ProjectName }}/{{ .Tag }}"
  - provider: s3
    bucket: oss-pkg.ibotta.com
    region: us-east-1
    folder: "{{ .ProjectName }}"
    extra_files:
      - glob: ./*install.sh

# dockers:
#   - id: amd64image
#     use: buildx
#     build_flag_templates:
#       - "--pull"
#       - "--platform=linux/amd64"
#       - "--label=org.label-schema.schema-version=1.0"
#       - "--label=org.label-schema.version={{.Version}}"
#       - "--label=org.label-schema.name={{.ProjectName}}"
#     goos: linux
#     # GOARCH of the built binary that should be used.
#     goarch: amd64
#     ids:
#       - sopstool
#     # Templates of the Docker image names.
#     image_templates:
#       # - "ibotta/{{ .ProjectName }}:latest"
#       # - "ibotta/{{ .ProjectName }}:{{ .Version }}"
#       # - "ibotta/{{ .ProjectName }}:{{ .Tag }}"
#       # - "ibotta/{{ .ProjectName }}:v{{ .Major }}"
#       # - "ibotta/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
#       - "ibotta/{{ .ProjectName }}:latest-amd64"
#       - "ibotta/{{ .ProjectName }}:{{ .Version }}-amd64"
#       - "ibotta/{{ .ProjectName }}:{{ .Tag }}-amd64"
#       - "ibotta/{{ .ProjectName }}:v{{ .Major }}-amd64"
#       - "ibotta/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
#       # - "ghcr.io/ibotta/{{ .ProjectName }}:latest"
#       # - "ghcr.io/ibotta/{{ .ProjectName }}:{{ .Version }}"
#       # - "ghcr.io/ibotta/{{ .ProjectName }}:{{ .Tag }}"
#       # - "ghcr.io/ibotta/{{ .ProjectName }}:v{{ .Major }}"
#       # - "ghcr.io/ibotta/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
#       - "ghcr.io/ibotta/{{ .ProjectName }}:latest-amd64"
#       - "ghcr.io/ibotta/{{ .ProjectName }}:{{ .Version }}-amd64"
#       - "ghcr.io/ibotta/{{ .ProjectName }}:{{ .Tag }}-amd64"
#       - "ghcr.io/ibotta/{{ .ProjectName }}:v{{ .Major }}-amd64"
#       - "ghcr.io/ibotta/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
#     # Skips the docker push. Could be useful if you also do draft releases.
#     # If set to auto, the release will not be pushed to the docker repository
#     # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
#     # Defaults to false.
#     skip_push: false
#     # Path to the Dockerfile (from the project root).
#     dockerfile: Dockerfile
#     # If your Dockerfile copies files other than the binary itself,
#     # you should list them here as well.
#     # Note that goreleaser will create the same structure inside the temporary
#     # folder, so if you add `foo/bar.json` here, on your Dockerfile you can
#     # `COPY foo/bar.json /whatever.json`.
#     # Also note that the paths here are relative to the folder in which
#     # goreleaser is being run.
#     # This field does not support wildcards, you can add an entire folder here
#     # and use wildcards when you `COPY`/`ADD` in your Dockerfile.
#     extra_files:
#       - sopsinstall.sh
#   - id: arm64image
#     use: buildx
#     build_flag_templates:
#       - "--pull"
#       - "--platform=linux/arm64"
#       - "--label=org.label-schema.schema-version=1.0"
#       - "--label=org.label-schema.version={{.Version}}"
#       - "--label=org.label-schema.name={{.ProjectName}}"
#     goos: linux
#     # GOARCH of the built binary that should be used.
#     goarch: arm64
#     # Name templates of the built binaries that should be used.
#     ids:
#       - sopstool
#     # Templates of the Docker image names.
#     image_templates:
#       - "ibotta/{{ .ProjectName }}:latest-arm64"
#       - "ibotta/{{ .ProjectName }}:{{ .Version }}-arm64"
#       - "ibotta/{{ .ProjectName }}:{{ .Tag }}-arm64"
#       - "ibotta/{{ .ProjectName }}:v{{ .Major }}-arm64"
#       - "ibotta/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
#       - "ghcr.io/ibotta/{{ .ProjectName }}:latest-arm64"
#       - "ghcr.io/ibotta/{{ .ProjectName }}:{{ .Version }}-arm64"
#       - "ghcr.io/ibotta/{{ .ProjectName }}:{{ .Tag }}-arm64"
#       - "ghcr.io/ibotta/{{ .ProjectName }}:v{{ .Major }}-arm64"
#       - "ghcr.io/ibotta/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
#     skip_push: false
#     dockerfile: Dockerfile
#     extra_files:
#       - sopsinstall.sh
