language: go
go:
  - "1.9"

services:
  - docker

addons:
  apt:
    packages:
      # needed for the nfpm pipe:
      - rpm

env:
  global:
    - AWS_REGION=us-east-1
    - AWS_DEFAULT_REGION=us-east-1
    - secure: "X6JDqwVHpwHMdqVAv64+lvNtGUWjb4/6hKGFV0LZClmREgfHNoLYlei/fNlAHpoQ3ssyiNn+8IJSyLihqhABXzJIQVbVP9LKXvG6WolaZFa7em3inBX84Eaf7TFexGxLrgsgrhOpTF/h2L+wIhDpNjv+cLU1jsqztHGUWq4MK8p/NpL762//zdrucpgPAlEs2kIjHDy8WuOYL92Z5DUjyfl6eZbl9D12JussKYCO59fv88ax4Gw16EL/pJSLXFzFLPXoklyz7WytoiLFeDEVHjjEgiCud+Fe3YKnyE58LSLqHjEjhu1Hl9JCmgMsLsBMeCN46hxDA/HJajTBgqaRMPQi9x/caG1FJsTiXC0gFHLkvnY3NA8aBcgk3b72D6WW8syc9UNvSensKDkV/WFXan0A2tIPW3TJDViOVoSy5l/sbzkKKaXEJZ9zmoKHXznJsptBP7MP2sidVGeh54BO8izkdgd1j64JIvIZafJP/4tyb37HsHBV2Rw5+7TRMM1g4Ww5964d4TEaSRiNvwVLparGR7POE3vh8SeHTo75AGfTRvanXoJz+jURQRe7oX4FluiUVVauvE84ldgdgs9EIcfWZq/r4PktpAQUvurOqvHFvmtDH3pj5IpN7rSpBrLJUqDZpjhrWFze5K1BiOBrEDhC3U14nN6Qr1m953+d++o=" #GH
    - secure: "gqr3U+nQubbot+I44iJaunIJCuV6DNcf+V1WINP5aIHzBGzGsuRyrwfi2nMzHoBdXIGPaOccB8zfTcZPQzshpQpzF6g9j0gsXsh0MIU3lOKyA1fxy6FKbe0lQm+8pg70XYYpM+aK5pajzAMXKaDB0uYRdUu5F+PpP6vYgHBe7W/qUEtGCOeftD82nYn8BlTLNBorLiTJ3EdGu5Ao70gBH+7pVhHrgAlaQDGZKSZcUYTuM5qwg83sldYTHPWYFxHRBvu/5PpcxaAJLYzPUp0DsDV4Eh4x4b/P/ThYSR8V2zDedz0nBKH/LjiGq1U1ta5uIjWNYC/0ENkTl3ykiPbh2/fdlgQhBT2iaDJEdBGEFWV7hErzGQAmDRAaM5OcT61n7zcj7v3supGdyWqGmhVMWhVbT8RMgjDGtWo8fWMrzu0RF4GRhevjQrf1McHzLaYLxVCG3FFRi/b71N/6bxnP4cDhYpGUBoNah01J5ynUoaaZ5KaF+POr9+8j8aVDcTfiibyVDKmH//S6qViPdLMP408Zyc8M2chmyODBYgSkaWHCnZIi4rtyZ1/J6NE3DIXekbNpGGhmLWLAUceNlxe+rupE2eNTlLCoK+knYyloeL3W8JIHZBzvuV3DymQAxm+0tVbVoi6Opuivm6GUL6epWi4UirEu9XgmNczgS8DPt8k=" #AWS_ID
    - secure: "MKopJn8iodm7wl+mYgOIiS5w+ZXH5tD4sgcW1fxeYMQk07spLZSFXG848hcproA+E4e9ItuwmbNNXRv8lIL4huV5KWxYrhghZFShNTCRTUaEn24zt6H9xyB6WSBGOugZu8ocbVmoCijuUCYPxIWIFwACwCHf/bGlOtqh9XBfQWIakXCNWKsa0PEI8UCPu+2NM4avxytu8HnuhnmkeRqe1DT9TNG/4D4ToGDGnG9gqKifUu5cZMkSU/8fwFlJT/32dI7IzHNQeclE/JQifHbtxs7lT45sYZ2mESeWBh3lCkylkTqwrUnIvBoRfOHz4rKU2xsfkRVZ4ASRBch+xO1cHsBxaF0/rc5K7QKfJO/0Enx7CdZzm3yxi9a/uokcOaw5Gkaq8a8GnmmBg3j7VB83buS9/RlXfMkxDYkCsmQq/l3J3czyutOS+ElshDZbVZqt0Ri7fXA5CKYdwFEwUOf1kitsTdjf2UBKp19C/svE3SDL7LY15qx9/lSv2xJlG0pbNmodAo1dPieYuZoRUHLHOowk4ybP7JWIXZdOyGZKbZzcDpaonAXEriG7mqrnVHxQJH/psXF2wB+mwJCcRJ9GD+Oen6vRKHlxszmqPpw3MJ/LKT8jjReqc3IT1qZP0HCF+uyN7pzXQRqfNLAYll0hP2f7cRtQZu5dQZFuzTFOmzw=" #AWS_SEC
    - secure: "fxQGy/it5W1NxCrpalz5K3UOZxAfvU9A0n7SoMUCHaK59dBmSWl1PyoyBkEFq3+bZqKqJjkyosn74RT5jQkOqm/nX38+EY/8GjG0Ds+okekrVP5ap6t313NeYALgApgxERZlK14/W6HWLYm8sAQNc7KHnnBroLt/KhIBJ7c0IKay4cPLunMegi+XOs4PjL+BOJ3hGoIWS2kShwIGqb0a0JkRh3gLXZUTyqlJ2AuzO859pAlMzfNqs6C/1R/U7dD2kBbKBhL0mbQ20OuKjPulis5ktcf5S7QRmUNWQE/MO62A2jVf/1+xjURuWiBHa/hKzh4dDXmJjaZgiJlOpZI4e9G24znoBgeiaEYvk5lQcSx88Y2w4FiJdXcLfssTT8pTJr/JCSozH34gNjW+tWScBJ5ERWnUdsPxU3q0MmhZe/XmRMa2N/Zw1APmUnfKvePNc2F4gL7KA7i1Nnje5EOaZSsPpSpC2Ev52mHKHiYqoq5Id4jQCSkxiImvCgepX/ccuzPq7wytaoOZ/nvhCGAh/mdJHUafaTVVFYeXXIe3jxEFRoKqiDY35F7cTqQ1y46YoQqWDxj9kRgBFJAp/Hd78dVMd0P0b2lSIaBrCyCeEGRbY8iuwACCxnBo+zWR+MkZUyMJRhResD8ZseZvqBpwWQHtcRUL5IvDMQkv95S+s3k=" #CC
    - secure: "ezJRO6jBp8u6x3ySeGD0Cu7hox/oYwHsn1A6Q9RMpK39rF0SDDf/36g2QN18a7u3ABbFFGKBAcj7d2WiUOxtZwRbRKzZEi0qhaIezzpuT3AATAMPi9Z/0s2JyPRkXU47dze4oqJkuraq13UJ1OLxrnaaUdLhQfCs1i5ooPGNlaZiTH0Z07C7ai+ylifm2rR+cas+2ltFWDc+xXyPaLPPCeKM8ql/p4nTMsWFePANG8OKDzYrCR8O4C4GDtPtEJfyAZHuHtVULXD2oZJZSbGpGdNKRA/1xoWsDMRk18Jc21E6uBJII4LdUlpCjSM2Pa4rAGo/z1mJG3E15ifmS6WOdOJHAkEMJtTEecZlGimrs4LCm34hW868vE6DSi+9U+YqENYoyFk+ABZ51c39yqfQxcXsmWHV8X9O/q5SggwRaH17RZqWXlNOCF6YCkOj6wDegwZ3Ghh9p96mci8eD59/ElLxD+ZAQRu/fEpUzDBJyS2bm2aDuPG6K+6dB6mAoXZDQOGR3OqVuL2m1UzDFCDoCQ2Y5sKOPZ7rQslC6x4SVcoZztd2xUCDDjDH08g1ztj8uqGhvaBZs9Yi+rfnNlMw9zpOrtlXP4LM0mqk+lISf4zyOc5WK3/biujSm3G2uEW3mloS0I0iRm0GYwB/f6Av1C2cFZFWaQB2xzzZ+/rD+GE=" #DH_LOGIN
    - secure: "UIIIDqIjhp96RQ9StO4VVBRUhBENrhapYsf0wcbGBiVq4sl2Ct4D5vIyRr67lS2mpym4wlQfXigjAIn6X9fReXnGLcmJHE3jTPDirTPITbsArtkWjm/0nbN+cV6edhPi3yAD5JkIYGfjBe0Kb0Ge7a1iEpwND5qE7LrxD5o6gdAMuPhCFW+lHWNRRTB7kAfPHugF0A38BeUbOOXLmd0OKadDMAJAC1csPpgrqcyttsUl5wV8FHtg2bewfCQWVpT7tt2zTcKuEbEws0COhZ8uOE9/xhiVY+07b3XO4DtN5emo8gi+J51B8brkyQnMeNLz+RtOl4pcrZ2okdYMyZEUQgxSA0lBiH0xIogqku5upJa+8BKl/XnEuh+sZ3ms5TPRLWCxtGR6gyeuKVQ+nNCxKsBppayV7Phz22OOfg8dRsekRfdTkhkpLc3NaqLinOW7khrClszX7bazJGVzNGGYEyI1Vj8NINx5wklzIxxdQ0ZdusqcMJbb2LlHsbS6o5m2TYw9w/zWFvE/lozlRjDxkR+I4WWxxjzY/REED6pa9v2lgbDjyMlry3hmV3vHyXoaYOLxmkIpZYO04mlGSB4vjdltTL0SZT98hN6G7h6Mnl9ELB/499cJUYAdlVF3WTrnlNcMpYEYrZ368ZbMixQgBc0xQycTP9/MInW7bX04DAI=" #DH_PW

before_install:
  # https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-use-dep-in-ci
  # Download the binary to bin folder in $GOPATH
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  # https://github.com/codeclimate/test-reporter#installation--usage
  # Download the binary to bin folder in $GOPATH
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > $GOPATH/bin/cc-test-reporter
  # Make the binary executable
  - chmod +x $GOPATH/bin/cc-test-reporter
  - mkdir tmp || true

install:
  # default is `go get -t ./...` - we override that with dep
  - dep ensure

script:
  # See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
  - 'if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then bash ./scripts/test; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/coverage_test; fi'

deploy:
  - provider: script
    # calls goreleaser
    skip_cleanup: true
    script: scripts/deploy
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
