language: go
go:
  - "1.9"

addons:
  apt:
    packages:
    # needed for the nfpm pipe:
    - rpm

env:
  global:
    - DEP_VERSION="0.4.1"
    - secure: "QjsvZRZRfaM/KTSlvUkaN0RE66vGxRE/8WABgIrDk7Idr8b0EEAarHeC9XFio3i75SKIyUZPjp/xT0MmZ9Re6Y63L2loIv0tsslPbRwa1oogWp8jDrSfVdlGAEElWSskNxFOtBm9sqaKR4shmUUoIvGkCNfLbuBhJFo5DwJ3708NqLZlqQ1veSYoUmjfnXIdcG/lF3Dg/GccNrXDLK6wGnprVhuEcpnPmEzuDKjSOI+wZRnRu2xx1nlQ2IEtB569j14/AekXLyQTBNGSXed5RXT6jiBcV0O80SfXv0KO+X5NluT1Dx0IjHNVGbisGNKUEzd6A7SLxrY+TG+I4JeGqt9skBeQpff8PCDrgCNcLTKLpHsPrTCBNpJLbgBVpHWp1cCVw/AiGHG/CBAIU4oar83Uwi6wBvGCtVVzR7LFkovZo3/BXet/VDXn423kHnri1PwRNFucPnabmuaG0QxyTPoIVm6/HKtcKbIMkF3CieDUsJLE4rY5ZAenF+7KUIZOtapdVZz5+/ryj+VwT+8UaprIjyUiKBAO76wcuPKlg5kAHv11lu5/LWT+N1f1jIzhnhW8jsSBgq/9EJXLDHLzBZWuiCaAqx4YVD+K+xlFFcFCR4VKPIOKrmGn7hgMoQlZ8PT+7OcsjKVLv7AA7wF7hMygHf6CWh0/TzaQ2//nl+A="

before_install:
  # https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-use-dep-in-ci
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  # default is `go get -t ./...` - we override that with dep
  - dep ensure

deploy:
- provider: script
  # calls goreleaser
  # TODO is this ok or does this need to be before_deploy or after_success
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: s3
  skip_cleanup: true
  access_key_id:
    secure:
  secret_access_key:
    secure:
  bucket: ibotta-oss
  local_dir: dist
  upload-dir: binaries/sopstool/
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

# after_deploy:
#   - update_latest_links
