#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# enable interruption signal handling
trap - INT TERM

docker run --rm \
  -t "$(tty &>/dev/null && echo "-i")" \
  -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
  -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
  -e "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" \
  -e "AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}" \
  -e "AWS_REGION=${AWS_REGION}" \
  -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" \
  -v "$(pwd):/project" \
  mesosphere/aws-cli \
  "$@"
