#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# enable interruption signal handling
trap - INT TERM

docker run --rm \
	-t $(tty &>/dev/null && echo "-i") \
	-e "AWS_ACCESS_KEY_ID" \
	-e "AWS_SECRET_ACCESS_KEY" \
	-e "AWS_REGION" \
	-e "AWS_DEFAULT_REGION" \
	-e "AWS_SESSION_TOKEN" \
	-e "AWS_SECURITY_TOKEN" \
	-v "$(pwd):/$(pwd)" \
	-w "$(pwd)" \
	mesosphere/aws-cli \
	"$@"
