#!/usr/bin/env bash
set -e

# directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# build environment
COMMIT_HASH=${TRAVIS_COMMIT:-$(git show -s --format=%h)}
COMMIT_HASH=${COMMIT_HASH::7}
COMMIT_STAMP=$(git show -s --format=%ct)
BUILD_STAMP=$(date +%s)

# build the flags
vflag() {
  VFLAGS="$VFLAGS -X $VERSION_PKG.$1=$2"
}

# build all flags for a package
pkgflag() {
  VFLAGS=""
  VERSION_PKG="$1/version"

  # TODO figure out a better way of doing the version number
  # MAIN_PKG=$(echo "$1" | sed 's/^.*\/\([^\/]*\)$/\1/')
  # BASE_VERSION=${TRAVIS_TAG:-$(git describe --tags --always --dirty=-dev --abbrev=0 --match="$MAIN_PKG@*")}
  # BASE_VERSION=$(echo "$BASE_VERSION" | sed 's/^.*@\([0-9a-z.\-]*\)$/\1/')

  # vflag Number ${BASE_VERSION}
  vflag CommitHash $COMMIT_HASH
  vflag CommitStamp $COMMIT_STAMP
  vflag BuildStamp $BUILD_STAMP
  vflag CiBuildNumber $TRAVIS_BUILD_NUMBER
  echo $VFLAGS
}

# get list of all 'main' packages
mainpkgs=`go list -f "{{.Name}}|{{.ImportPath}}" ./... | grep main | sed 's/main|//'`

for f in $mainpkgs; do
  # build package with flags
  gox -output "dist/{{.OS}}/{{.Arch}}/{{.Dir}}" -osarch "darwin/amd64 linux/amd64 linux/386" -ldflags "$(pkgflag $f)" $f
done

# copy install script(s)
cp -v $DIR/install_* dist/
