#!/bin/sh
set -e

mkdir -p tmp
for pkg in $(go list ./...); do
  go test -coverprofile="./tmp/$(echo "$pkg" | tr / -).cover" "$pkg"
done

echo "mode: set" > c.out
grep -h -v "^mode:" ./tmp/*.cover >> c.out
rm -f ./tmp/*.cover
