#!/usr/bin/env bash
set -e
set -o errexit
set -o nounset
set -o pipefail

# enable interruption signal handling
trap - INT TERM

S3URL="s3://oss-pkg.ibotta.com"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# ensure we are in the project root for all the work
cd "$DIR/.."

if [ ! -e dist/sopstool_checksums.txt ]; then
  echo "Did not build checksums" && exit 1
fi

# download sops for reupload to s3
SOPSDIST="dist/sops"
if [ -d "$SOPSDIST" ]; then
  rm -rf "$SOPSDIST"
fi

mkdir -p "$SOPSDIST"
$DIR/../sopsinstall.sh -o linux -a amd64 -z "$SOPSDIST"
$DIR/../sopsinstall.sh -o linux -a arm64 -z "$SOPSDIST"
$DIR/../sopsinstall.sh -o darwin -a amd64 -z "$SOPSDIST"
$DIR/../sopsinstall.sh -o darwin -a arm64 -z "$SOPSDIST"
$DIR/../sopsinstall.sh -o windows -a amd64 -z "$SOPSDIST"

# put those on s3
aws s3 cp --recursive "$SOPSDIST/" "$S3URL/sops/"
