#!/bin/bash
set -e
set -o errexit
set -o nounset
set -o pipefail

# enable interruption signal handling
trap - INT TERM

S3URL="s3://oss-pkg.ibotta.com"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# docker login
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# ensure we are in the project root for all the work
cd "$DIR/.."

# run goreleaser
goreleaser

if [ ! -e dist/sopstool_checksums.txt ]; then
  echo "Did not build checksums" && exit 1
fi

# also copy up installers
aws s3 cp sopsinstall.sh "$S3URL/sopstool/"
aws s3 cp sopstoolinstall.sh "$S3URL/sopstool/"
aws s3 cp install.sh "$S3URL/sopstool/"

# download sops for reupload to s3
SOPSDIST="dist/sops"
if [ -d "$SOPSDIST" ]; then
  rm -rf "$SOPSDIST"
fi

mkdir -p "$SOPSDIST"
$DIR/sopsdownload.sh -o linux "$SOPSDIST"
$DIR/sopsdownload.sh -o darwin "$SOPSDIST"

# put those on s3
aws s3 cp --recursive "$SOPSDIST/" "$S3URL/sops/"
