#!/bin/bash
set -e
set -o errexit
set -o nounset
set -o pipefail

# enable interruption signal handling
trap - INT TERM

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

curl -sL http://git.io/goreleaser | bash

if [ -e dist/sopstool_checksums.txt ]; then
  #also copy up installers
  $DIR/aws s3 cp sopsinstall.sh s3://oss-pkg.ibotta.com/sopstool/
  $DIR/aws s3 cp sopstoolinstall.sh s3://oss-pkg.ibotta.com/sopstool/
  $DIR/aws s3 cp install.sh s3://oss-pkg.ibotta.com/sopstool/
else
  echo "Did not build checksums" && exit 1
fi
