#!/usr/bin/env bash
set -e
set -o errexit
set -o nounset
set -o pipefail

# enable interruption signal handling
trap - INT TERM

REGEX="^v([0-9]+)\.([0-9]+)\.([0-9]+)"
export VERSION=$(jq -r '.version' dist/metadata.json)
export TAG=$(jq -r '.tag' dist/metadata.json)
if [[ "${TAG}" =~ ${REGEX} ]]; then
	export RAWVERSION=${BASH_REMATCH[0]}
	export MAJOR=${BASH_REMATCH[1]}
	export MINOR=${BASH_REMATCH[2]}
	export PATCH=${BASH_REMATCH[3]}
fi

docker buildx bake --metadata-file dist/bake.json --sbom=true "$@"
