name: test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: mod download
        run: go mod download && go build

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: go test ./... -coverprofile c.out
          prefix: github.com/Ibotta/sopstool

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot --skip-publish

      - name: Test Docker
        run: scripts/deploy-docker
