name: release

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # todo install rpm, nfpm, golangci, awscli
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: mod download
        shell: bash
        run: go mod download && go build
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist --snapshot --skip-publish
